---
- hosts: all
  gather_facts: no
  vars:
    appsrc: "{{ lookup('env','WORKSPACE') }}/target/"
  tasks:
    - name: copy WAR file to APP servers.
      copy: 
        src: "{{ item }}"
        dest: /opt/tomcat/webapps/app.war
        follow: no
      with_fileglob:
        - "{{ appsrc }}/*war"
 
    - name: stop tomcat application
      systemd:
        name: tomcat
        state: stopped
    
    - name: start tomcat application
      systemd:
        name: tomcat
        state: started    
   