---
- hosts: all
  gather_facts: no
  tasks:
    - name: copy WAR file to APP servers.
      copy: 
        src: "{{ WORKSPACE }}/target/*.war"
        dest: /opt/tomcat/webapps
    
    - name: stop tomcat application
      systemd:
        name: tomcat
        state: stopped
    
    - name: start tomcat application
      systemd:
        name: tomcat
        state: started    
   