---
- hosts: all
  gather_facts: no
  tasks:
    - name: copy WAR file to APP servers.
      copy: 
        src: "{{ item }}"
        src: "{{ lookup('env','WORKSPACE') }}/target/*.war"
        dest: /opt/tomcat/webapps
      with_fileglob:
        - '"{{ lookup('env','WORKSPACE') }}/target/*.war"'
 
    - name: stop tomcat application
      systemd:
        name: tomcat
        state: stopped
    
    - name: start tomcat application
      systemd:
        name: tomcat
        state: started    
   