---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: install java on servers
      yum: 
        name: "{{ item }}"
        state: present
      with_items:
        - java-1.8.0-openjdk.x86_64
        - wget
        - unzip
        